#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
PROTOTYPE_DIR=$(cd -- "$SCRIPT_DIR/.." && pwd -P)
EXTENSION="$SCRIPT_DIR/live-role-label-extension.ts"
RUNNER_CLI="$PROTOTYPE_DIR/src/cli.ts"
GATE_MODEL="${OMARCHESTRA_GATE_MODEL:-openai-codex/gpt-5.6-sol}"
GATE_PASS=1
GATE_COMPLETED=0
CLEANED=0
RUNTIME_DIR=""
EVIDENCE_DIR=""
RUNNER_PID=""
GHOSTTY_PIDS=()
ROLES=(coordinator builder reviewer)

if [[ "${1:-}" == "--check" ]]; then
  [[ -f "$EXTENSION" && -f "$SCRIPT_DIR/live-bridge-core.ts" && -f "$RUNNER_CLI" ]]
  [[ "$GATE_MODEL" =~ ^[A-Za-z0-9._~-]+/[A-Za-z0-9._:~-]+$ ]]
  printf 'manual role-label wizard static check: PASS\n'
  exit 0
fi

append_observation() {
  printf '%s\n' "$1" >> "$EVIDENCE_DIR/observations.md"
}

terminate_exact() {
  local pid="$1" needle="$2" label="$3" cmdline=""
  [[ -n "$pid" && -r "/proc/$pid/cmdline" ]] || return 0
  cmdline=$(tr '\0' ' ' < "/proc/$pid/cmdline")
  if [[ "$cmdline" != *"$needle"* ]]; then
    warn "refusing to terminate $label PID $pid: identity no longer matches"
    return 1
  fi
  kill -TERM "$pid" 2>/dev/null || true
  for _ in $(seq 1 50); do
    [[ ! -e "/proc/$pid" ]] && return 0
    sleep 0.1
  done
  kill -KILL "$pid" 2>/dev/null || true
}

cleanup() {
  local role pid launcher safe=1
  (( CLEANED == 0 )) || return 0
  CLEANED=1
  set +e
  if [[ "$GATE_COMPLETED" -eq 0 && -n "$EVIDENCE_DIR" && -f "$EVIDENCE_DIR/observations.md" ]]; then
    append_observation ""
    append_observation "## Verdict"
    append_observation "**ABORTED — operator or runtime stopped before the terminal-side gate completed.**"
    append_observation ""
    append_observation "- Aborted: $(date --iso-8601=seconds)"
  fi
  for role in "${ROLES[@]}"; do
    if [[ -n "$RUNTIME_DIR" && -f "$RUNTIME_DIR/$role.pid" ]]; then
      pid=$(<"$RUNTIME_DIR/$role.pid")
      terminate_exact "$pid" "$EXTENSION" "$role visible Pi" || safe=0
    fi
  done
  if [[ -n "$RUNNER_PID" ]]; then
    terminate_exact "$RUNNER_PID" "$RUNNER_CLI" "foreground runner" || safe=0
  fi
  for launcher in "${GHOSTTY_PIDS[@]}"; do
    terminate_exact "$launcher" "com.omarchestra.ManualGate" "Ghostty gate window" || safe=0
  done
  if [[ -n "$RUNTIME_DIR" && -d "$RUNTIME_DIR" && "$safe" -eq 1 ]]; then
    rm -rf -- "$RUNTIME_DIR"
  elif [[ -n "$RUNTIME_DIR" && -d "$RUNTIME_DIR" ]]; then
    warn "preserved runtime for safe manual reconciliation: $RUNTIME_DIR"
  fi
}
trap cleanup EXIT

record_exact_surfaces() {
  local checkpoint="$1" coordinator_state="$2" builder_state="$3" reviewer_state="$4"
  local timestamp role display state
  timestamp=$(date --iso-8601=seconds)
  for role in "${ROLES[@]}"; do
    case "$role" in
      coordinator) display=Coordinator; state="$coordinator_state" ;;
      builder) display=Builder; state="$builder_state" ;;
      reviewer) display=Reviewer; state="$reviewer_state" ;;
    esac
    append_observation "| $checkpoint | $timestamp | $display | terminal title metadata | \`Omarchestra — $display — $state\` |"
    append_observation "| $checkpoint | $timestamp | $display | Pi status | \`$display · $state\` |"
  done
}

record_confirmation() {
  local checkpoint="$1" prompt="$2" note_text=""
  if confirm "$prompt"; then
    append_observation "- **$checkpoint:** PASS — human confirmed at $(date --iso-8601=seconds)"
  else
    GATE_PASS=0
    ask note_text "Briefly describe what differed:"
    append_observation "- **$checkpoint:** FAIL — ${note_text:-no note supplied} ($(date --iso-8601=seconds))"
  fi
}

title_metadata_matches() {
  local role="$1" state="$2" display expected actual
  case "$role" in
    coordinator) display=Coordinator ;;
    builder) display=Builder ;;
    reviewer) display=Reviewer ;;
  esac
  expected="Omarchestra — $display — $state"
  actual=$(hyprctl clients -j | jq -r \
    --arg class "com.omarchestra.ManualGate.$role" \
    '[.[] | select(.class == $class) | .title][0] // ""')
  [[ "$actual" == "$expected" ]]
}

status_matches() {
  local role="$1" state="$2" display
  case "$role" in
    coordinator) display=Coordinator ;;
    builder) display=Builder ;;
    reviewer) display=Reviewer ;;
  esac
  node - "$RUNTIME_DIR/$role.status.json" "$role" "$display" "$state" <<'NODE'
const fs = require('node:fs')
const [file, role, display, state] = process.argv.slice(2)
try {
  const value = JSON.parse(fs.readFileSync(file, 'utf8'))
  const ok = value.role === role &&
    value.nativeTerminalTitle === `Omarchestra — ${display} — ${state}` &&
    value.piStatus === `${display} · ${state}`
  process.exit(ok ? 0 : 1)
} catch {
  process.exit(1)
}
NODE
}

wait_for_states() {
  local coordinator_state="$1" builder_state="$2" reviewer_state="$3" attempt
  for attempt in $(seq 1 450); do
    if status_matches coordinator "$coordinator_state" &&
       status_matches builder "$builder_state" &&
       status_matches reviewer "$reviewer_state" &&
       title_metadata_matches coordinator "$coordinator_state" &&
       title_metadata_matches builder "$builder_state" &&
       title_metadata_matches reviewer "$reviewer_state"; then
      return 0
    fi
    sleep 0.1
  done
  return 1
}

capture_checkpoint() {
  local checkpoint="$1" role
  hyprctl clients -j > "$EVIDENCE_DIR/$checkpoint-hyprland-clients.json"
  chmod 600 "$EVIDENCE_DIR/$checkpoint-hyprland-clients.json"
  for role in "${ROLES[@]}"; do
    cp -- "$RUNTIME_DIR/$role.status.json" "$EVIDENCE_DIR/$checkpoint-$role-presentation.json"
    chmod 600 "$EVIDENCE_DIR/$checkpoint-$role-presentation.json"
  done
}

prepare_live_gate() {
  local role pid_file session_id
  umask 077
  for command in node pi ghostty hyprctl jq; do
    command -v "$command" >/dev/null 2>&1 || { warn "missing required command: $command"; return 1; }
  done
  [[ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]] || { warn "no active Hyprland session"; return 1; }
  [[ "$GATE_MODEL" =~ ^[A-Za-z0-9._~-]+/[A-Za-z0-9._:~-]+$ ]] || { warn "invalid gate model identifier"; return 1; }

  RUNTIME_DIR=$(mktemp -d "${XDG_RUNTIME_DIR:-/tmp}/omarchestra-role-label-gate.XXXXXX")
  chmod 700 "$RUNTIME_DIR"
  EVIDENCE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/omarchestra/manual-gates/$(date +%Y%m%dT%H%M%S)-$$"
  mkdir -p -- "$EVIDENCE_DIR"
  chmod 700 "$EVIDENCE_DIR"
  printf '%s\n' "$GATE_MODEL" > "$EVIDENCE_DIR/model.txt"
  chmod 600 "$EVIDENCE_DIR/model.txt"

  cat > "$RUNTIME_DIR/pi-host.sh" <<'HOST'
#!/usr/bin/env bash
set -euo pipefail
role="$1"
runtime="$2"
prototype="$3"
extension="$4"
model="$5"
printf '%s\n' "$$" > "$runtime/$role.pid"
chmod 600 "$runtime/$role.pid"
while [[ ! -e "$runtime/start-pi" ]]; do sleep 0.05; done
session_id=$(<"$runtime/$role.session-id")
exec env \
  OMARCHESTRA_TEAM_GOAL_ID="manual-role-label-goal" \
  OMARCHESTRA_ROLE="$role" \
  OMARCHESTRA_AGENT_RUN_ID="manual-$role-run" \
  OMARCHESTRA_EXTENSION_INSTANCE_ID="manual-$role-extension" \
  OMARCHESTRA_TERMINAL_SESSION_REF="manual-$role-terminal" \
  OMARCHESTRA_SHELL_RUN_ID="manual-$role-shell" \
  OMARCHESTRA_PI_SESSION_ID="$session_id" \
  OMARCHESTRA_BRIDGE_SOCKET="$runtime/runner.sock" \
  OMARCHESTRA_GATE_STATUS_FILE="$runtime/$role.status.json" \
  pi --no-extensions --no-approve --no-context-files --no-tools \
    --model "$model" --thinking minimal \
    --session-id "$session_id" --session-dir "$runtime/sessions/$role" \
    -e "$extension"
HOST
  chmod 700 "$RUNTIME_DIR/pi-host.sh"

  mkdir -p -- "$RUNTIME_DIR/sessions"
  chmod 700 "$RUNTIME_DIR/sessions"
  for role in "${ROLES[@]}"; do
    mkdir -p -- "$RUNTIME_DIR/sessions/$role"
    chmod 700 "$RUNTIME_DIR/sessions/$role"
    session_id=$(node -e "process.stdout.write(require('node:crypto').randomUUID())")
    printf '%s\n' "$session_id" > "$RUNTIME_DIR/$role.session-id"
    chmod 600 "$RUNTIME_DIR/$role.session-id"
    ghostty \
      --class="com.omarchestra.ManualGate.$role" \
      --window-decoration=none \
      -e "$RUNTIME_DIR/pi-host.sh" "$role" "$RUNTIME_DIR" "$PROTOTYPE_DIR" "$EXTENSION" "$GATE_MODEL" \
      >> "$EVIDENCE_DIR/ghostty-launch.log" 2>&1 &
    GHOSTTY_PIDS+=("$!")
  done

  for role in "${ROLES[@]}"; do
    pid_file="$RUNTIME_DIR/$role.pid"
    for _ in $(seq 1 150); do [[ -s "$pid_file" ]] && break; sleep 0.1; done
    [[ -s "$pid_file" ]] || { warn "$role visible host did not publish its PID"; return 1; }
  done

  BOOTSTRAP_JSON=$(RUNTIME_DIR="$RUNTIME_DIR" node <<'NODE'
const fs = require('node:fs')
const path = require('node:path')
const runtime = process.env.RUNTIME_DIR
const roles = ['coordinator', 'builder', 'reviewer'].map((role) => ({
  role,
  agentRunId: `manual-${role}-run`,
  terminalSessionRef: `manual-${role}-terminal`,
  shellRunId: `manual-${role}-shell`,
  piSessionId: fs.readFileSync(path.join(runtime, `${role}.session-id`), 'utf8').trim(),
  extensionInstanceId: `manual-${role}-extension`,
  hostPid: Number(fs.readFileSync(path.join(runtime, `${role}.pid`), 'utf8').trim()),
}))
process.stdout.write(JSON.stringify({
  teamGoalId: 'manual-role-label-goal',
  goalText: 'Authorized local human gate for persistent role and control-state labels.',
  roles,
  assignment: {
    id: 'manual-builder-assignment',
    role: 'builder',
    agentRunId: 'manual-builder-run',
    prompt: 'Reply with exactly: MANAGED BUILDER TURN COMPLETE',
  },
}))
NODE
)

  NODE_FLAGS=()
  node --help | grep -q -- '--experimental-sqlite' && NODE_FLAGS+=(--experimental-sqlite) || true
  node --help | grep -q -- '--experimental-strip-types' && NODE_FLAGS+=(--experimental-strip-types) || true
  node "${NODE_FLAGS[@]}" "$RUNNER_CLI" \
    --state-dir "$RUNTIME_DIR/state" \
    --socket-name runner.sock \
    --journal default \
    --bootstrap-json "$BOOTSTRAP_JSON" \
    > "$EVIDENCE_DIR/runner.ndjson" 2>&1 &
  RUNNER_PID=$!
  printf '%s\n' "$RUNNER_PID" > "$EVIDENCE_DIR/runner.pid"
  chmod 600 "$EVIDENCE_DIR/runner.ndjson" "$EVIDENCE_DIR/runner.pid"

  for _ in $(seq 1 150); do [[ -S "$RUNTIME_DIR/state/runner.sock" ]] && break; sleep 0.1; done
  [[ -S "$RUNTIME_DIR/state/runner.sock" ]] || { warn "runner socket did not become ready"; return 1; }
  # The extension expects this stable path; the runner socket lives under state.
  ln -s "$RUNTIME_DIR/state/runner.sock" "$RUNTIME_DIR/runner.sock"
  touch "$RUNTIME_DIR/start-pi"
  chmod 600 "$RUNTIME_DIR/start-pi"
  wait_for_states waiting waiting waiting || { warn "visible Pi hosts did not reach exact waiting labels"; return 1; }

  cat > "$EVIDENCE_DIR/observations.md" <<EOF
# Omarchestra local manual role-label gate

- Started: $(date --iso-8601=seconds)
- Model: \`$GATE_MODEL\`
- Runtime: private and removed after exact cleanup
- Evidence: private, mode 0700, outside Git

| Checkpoint | Timestamp | Role | Surface | Expected string applied/verified |
| --- | --- | --- | --- | --- |
EOF
  chmod 600 "$EVIDENCE_DIR/observations.md"
}

banner "Omarchestra local role-label gate"

stage "Launch three visible Pi hosts"
say "This opens decorationless Coordinator, Builder, and Reviewer Pi TUIs."
say "The Builder assignment is queued but deliberately not accepted yet."
prepare_live_gate
capture_checkpoint idle
record_exact_surfaces idle waiting waiting waiting
step "Without reading conversation content, inspect the three Pi footer statuses."
step "Expected: Coordinator · waiting, Builder · waiting, Reviewer · waiting."
note "The controller separately verifies matching dynamic terminal metadata through Hyprland."
record_confirmation "idle Pi-status identification" "Do all three Pi statuses exactly match and remain mutually distinct?"

stage "Confirm the Omarchy-native presentation"
step "Confirm the three agent terminals remain decorationless and visually native to Omarchy."
step "Use the Pi statuses alone to identify Coordinator, Builder, and Reviewer."
note "The future Agent Console is the redundant team-wide visual surface; it is not live in this prototype."
record_confirmation "decorationless Pi-status sufficiency" "Are the decorationless windows acceptable and the Pi statuses independently sufficient?"

stage "Enter managed Builder state"
step "Focus the Builder terminal and enter exactly: /omarchestra-start"
step "Wait for the visible Builder turn to reply: MANAGED BUILDER TURN COMPLETE."
pause "Return to this controller and press Enter."
wait_for_states waiting managed waiting || { warn "runner did not reach waiting/managed/waiting"; exit 1; }
capture_checkpoint managed
record_exact_surfaces managed waiting managed waiting
step "Builder Pi status must say managed; Coordinator and Reviewer must remain waiting."
note "Matching title metadata is verified automatically but is not treated as persistent chrome."
record_confirmation "managed transition and sibling isolation" "Do the three Pi statuses exactly match the managed checkpoint?"

stage "Submit manual takeover"
step "Focus the Builder terminal and enter exactly: Manual takeover check"
step "The extension records this ordinary interactive submission but suppresses a second model request."
pause "Return to this controller and press Enter."
wait_for_states waiting manual_takeover waiting || { warn "runner did not reach waiting/manual_takeover/waiting"; exit 1; }
capture_checkpoint takeover
record_exact_surfaces takeover waiting manual_takeover waiting
record_confirmation "manual takeover and sibling isolation" "Does only the Builder Pi status show manual_takeover?"

stage "One-minute persistence"
say "Leave all four windows idle. Labels must stay visible and must not be overwritten."
for remaining in 60 45 30 15; do
  note "$remaining seconds remaining…"
  sleep 15
 done
wait_for_states waiting manual_takeover waiting || { warn "labels changed during persistence interval"; exit 1; }
capture_checkpoint persisted
record_exact_surfaces persisted waiting manual_takeover waiting
record_confirmation "one-minute persistence" "After one minute, are all three Pi statuses still visible, exact, and distinct?"

stage "Record the verdict and clean up"
say "Private evidence was written outside Git. No screenshot was taken."
if (( GATE_PASS == 1 )); then
  say "Provisional verdict: PASS"
else
  warn "Provisional verdict: FAIL"
fi
record_confirmation "operator verdict confirmation" "Is the provisional verdict accurate?"
append_observation ""
append_observation "## Verdict"
if (( GATE_PASS == 1 )); then
  append_observation "**TERMINAL-SIDE PASS — Pi statuses and dynamic terminal metadata confirmed; live Agent Console redundancy remains pending.**"
else
  append_observation "**FAIL — one or more terminal-side criteria were not confirmed.**"
fi
append_observation ""
append_observation "- Completed: $(date --iso-8601=seconds)"
append_observation "- Exact cleanup: requested by controller exit trap"
step "Evidence directory: $EVIDENCE_DIR"
GATE_COMPLETED=1

finish
say "Gate result: $([[ "$GATE_PASS" -eq 1 ]] && echo PASS || echo FAIL)"
say "Private evidence: $EVIDENCE_DIR"
pause "Press Enter to close the gate windows and perform exact cleanup."

(( GATE_PASS == 1 ))
